# fly.toml app configuration file generated for green-bush-3732 on 2024-01-20T12:51:37+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "green-bush-3732"
primary_region = "nrt"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
